import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Estudiantes miEstudiante;
        Estudiantes miEstudiante2;
        Estudiantes miEstudiante3;
        Estudiantes miEstudiante4;
        Estudiantes miEstudiante5;
        Estudiantes miEstudiante6;
        Estudiantes miEstudiante7;
        Estudiantes miEstudiante8;
        Estudiantes miEstudiante9;
        Estudiantes miEstudiante10;
        miEstudiante=new Estudiantes("Francisco",36541);
        miEstudiante2=new Estudiantes("Juan",12345);
        miEstudiante3=new Estudiantes("Marta",87541);
        miEstudiante4=new Estudiantes("Raul",54126);
        miEstudiante5=new Estudiantes("Luis",45718);
        miEstudiante6=new Estudiantes("Sofia",78541);
        miEstudiante7=new Estudiantes("Manuel",78451);
        miEstudiante8=new Estudiantes("Ana",14598);
        miEstudiante9=new Estudiantes("Roberto",12784);
        miEstudiante10=new Estudiantes("Cristiano",32178);
        Scanner miVariable=new Scanner(System.in);
        Scanner miVariable2=new Scanner(System.in);
        Scanner miVariable3=new Scanner(System.in);
        System.out.println(miEstudiante.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        String materia1=miVariable.nextLine();
        miEstudiante.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante.getNomMateria1());
        double nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante.getNomMateria1());
        double nota2=miVariable3.nextDouble();
        double notaFinal=(nota1+nota2)/2;
        miEstudiante.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante.getNomMateria1()+" : "+ miEstudiante.getMateria1());
        System.out.println(miEstudiante.promedio1(miEstudiante.materia1));

        // segunda materia

        System.out.println("Ingrese el nombre de la segunda materia: ");
        String materia2=miVariable.nextLine();
        miEstudiante.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante.getNomMateria2()+" : "+ miEstudiante.getMateria2());
        System.out.println(miEstudiante.promedio2(miEstudiante.materia2));

        // tercera materia

        System.out.println("Ingrese el nombre de la tercera materia: ");
        String materia3=miVariable.nextLine();
        miEstudiante.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante.getNomMateria3());
        nota1=miVariable3.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante.getNomMateria3()+" : "+ miEstudiante.getMateria3());
        System.out.println(miEstudiante.promedio3(miEstudiante.materia3));

        // cuarta materia

        System.out.println("Ingrese el nombre de la cuarta materia: ");
        String materia4=miVariable.nextLine();
        miEstudiante.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante.getNomMateria4());
        nota1=miVariable3.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante.getNomMateria4()+" : "+ miEstudiante.getMateria4());
        System.out.println(miEstudiante.promedio4(miEstudiante.materia4));

        // quinta materia

        System.out.println("Ingrese el nombre de la quinta materia: ");
        String materia5=miVariable.nextLine();
        miEstudiante.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante.getNomMateria5());
        nota1=miVariable3.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante.getNomMateria5()+" : "+ miEstudiante.getMateria5());
        System.out.println(miEstudiante.promedio5(miEstudiante.materia5));
        //Estudiante 2
        System.out.println(miEstudiante2.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante2.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante2.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante2.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante2.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante2.getNomMateria1()+" : "+ miEstudiante2.getMateria1());
        System.out.println(miEstudiante2.promedio1(miEstudiante2.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante2.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante2.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante2.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante2.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante2.getNomMateria2()+" : "+ miEstudiante2.getMateria2());
        System.out.println(miEstudiante2.promedio2(miEstudiante2.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante2.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante2.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante2.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante2.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante2.getNomMateria3()+" : "+ miEstudiante2.getMateria3());
        System.out.println(miEstudiante2.promedio3(miEstudiante2.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante2.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante2.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante2.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante2.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante2.getNomMateria4()+" : "+ miEstudiante2.getMateria4());
        System.out.println(miEstudiante2.promedio4(miEstudiante2.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante2.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante2.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante2.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante2.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante2.getNomMateria5()+" : "+ miEstudiante2.getMateria5());
        System.out.println(miEstudiante2.promedio5(miEstudiante2.materia5));
        //Tercero
        System.out.println(miEstudiante3.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante3.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante3.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante3.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante3.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante3.getNomMateria1()+" : "+ miEstudiante3.getMateria1());
        System.out.println(miEstudiante3.promedio1(miEstudiante3.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante3.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante3.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante3.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante3.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante3.getNomMateria2()+" : "+ miEstudiante3.getMateria2());
        System.out.println(miEstudiante3.promedio2(miEstudiante3.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante3.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante3.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante3.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante3.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante3.getNomMateria3()+" : "+ miEstudiante3.getMateria3());
        System.out.println(miEstudiante3.promedio3(miEstudiante3.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante3.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante3.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante3.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante3.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante3.getNomMateria4()+" : "+ miEstudiante3.getMateria4());
        System.out.println(miEstudiante3.promedio4(miEstudiante3.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante3.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante3.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante3.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante3.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante3.getNomMateria5()+" : "+ miEstudiante3.getMateria5());
        System.out.println(miEstudiante3.promedio5(miEstudiante3.materia5));

        System.out.println(miEstudiante4.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante4.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante4.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante4.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante4.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante4.getNomMateria1()+" : "+ miEstudiante4.getMateria1());
        System.out.println(miEstudiante4.promedio1(miEstudiante4.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante4.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante4.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante4.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante4.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante4.getNomMateria2()+" : "+ miEstudiante4.getMateria2());
        System.out.println(miEstudiante4.promedio2(miEstudiante4.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante4.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante4.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante4.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante4.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante4.getNomMateria3()+" : "+ miEstudiante4.getMateria3());
        System.out.println(miEstudiante4.promedio3(miEstudiante4.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante4.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante4.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante4.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante4.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante4.getNomMateria4()+" : "+ miEstudiante4.getMateria4());
        System.out.println(miEstudiante4.promedio4(miEstudiante4.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante4.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante4.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante4.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante4.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante4.getNomMateria5()+" : "+ miEstudiante4.getMateria5());
        System.out.println(miEstudiante4.promedio5(miEstudiante4.materia5));

        System.out.println(miEstudiante5.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante5.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante5.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante5.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante5.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante5.getNomMateria1()+" : "+ miEstudiante5.getMateria1());
        System.out.println(miEstudiante5.promedio1(miEstudiante5.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante5.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante5.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante5.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante5.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante5.getNomMateria2()+" : "+ miEstudiante5.getMateria2());
        System.out.println(miEstudiante5.promedio2(miEstudiante5.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante5.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante5.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante5.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante5.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante5.getNomMateria3()+" : "+ miEstudiante5.getMateria3());
        System.out.println(miEstudiante5.promedio3(miEstudiante5.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante5.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante5.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante5.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante5.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante5.getNomMateria4()+" : "+ miEstudiante5.getMateria4());
        System.out.println(miEstudiante5.promedio4(miEstudiante5.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante5.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante5.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante5.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante5.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante5.getNomMateria5()+" : "+ miEstudiante5.getMateria5());
        System.out.println(miEstudiante5.promedio5(miEstudiante5.materia5));

        System.out.println(miEstudiante6.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante6.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante6.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante6.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante6.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante6.getNomMateria1()+" : "+ miEstudiante6.getMateria1());
        System.out.println(miEstudiante6.promedio1(miEstudiante6.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante6.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante6.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante6.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante6.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante6.getNomMateria2()+" : "+ miEstudiante6.getMateria2());
        System.out.println(miEstudiante6.promedio2(miEstudiante6.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante6.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante6.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante6.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante6.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante6.getNomMateria3()+" : "+ miEstudiante6.getMateria3());
        System.out.println(miEstudiante6.promedio3(miEstudiante6.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante6.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante6.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante6.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante6.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante6.getNomMateria4()+" : "+ miEstudiante6.getMateria4());
        System.out.println(miEstudiante6.promedio4(miEstudiante6.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante6.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante6.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante6.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante6.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante6.getNomMateria5()+" : "+ miEstudiante6.getMateria5());
        System.out.println(miEstudiante6.promedio5(miEstudiante6.materia5));

        System.out.println(miEstudiante7.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante7.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante7.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante7.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante7.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante7.getNomMateria1()+" : "+ miEstudiante7.getMateria1());
        System.out.println(miEstudiante7.promedio1(miEstudiante7.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante7.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante7.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante7.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante7.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante7.getNomMateria2()+" : "+ miEstudiante7.getMateria2());
        System.out.println(miEstudiante7.promedio2(miEstudiante7.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante7.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante7.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante7.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante7.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante7.getNomMateria3()+" : "+ miEstudiante7.getMateria3());
        System.out.println(miEstudiante7.promedio3(miEstudiante7.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante7.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante7.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante7.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante7.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante7.getNomMateria4()+" : "+ miEstudiante7.getMateria4());
        System.out.println(miEstudiante7.promedio4(miEstudiante7.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante7.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante7.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante7.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante7.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante7.getNomMateria5()+" : "+ miEstudiante7.getMateria5());
        System.out.println(miEstudiante7.promedio5(miEstudiante7.materia5));

        System.out.println(miEstudiante8.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante8.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante8.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante8.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante8.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante8.getNomMateria1()+" : "+ miEstudiante8.getMateria1());
        System.out.println(miEstudiante8.promedio1(miEstudiante8.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante8.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante8.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante8.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante8.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante8.getNomMateria2()+" : "+ miEstudiante8.getMateria2());
        System.out.println(miEstudiante8.promedio2(miEstudiante8.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante8.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante8.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante8.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante8.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante8.getNomMateria3()+" : "+ miEstudiante8.getMateria3());
        System.out.println(miEstudiante8.promedio3(miEstudiante8.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante8.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante8.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante8.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante8.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante8.getNomMateria4()+" : "+ miEstudiante8.getMateria4());
        System.out.println(miEstudiante8.promedio4(miEstudiante8.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante8.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante8.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante8.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante8.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante8.getNomMateria5()+" : "+ miEstudiante8.getMateria5());
        System.out.println(miEstudiante8.promedio5(miEstudiante8.materia5));

        System.out.println(miEstudiante9.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante9.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante9.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante9.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante9.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante9.getNomMateria1()+" : "+ miEstudiante9.getMateria1());
        System.out.println(miEstudiante9.promedio1(miEstudiante9.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante9.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante9.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante9.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante9.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante9.getNomMateria2()+" : "+ miEstudiante9.getMateria2());
        System.out.println(miEstudiante9.promedio2(miEstudiante9.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante9.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante9.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante9.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante9.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante9.getNomMateria3()+" : "+ miEstudiante9.getMateria3());
        System.out.println(miEstudiante9.promedio3(miEstudiante9.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante9.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante9.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante9.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante9.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante9.getNomMateria4()+" : "+ miEstudiante9.getMateria4());
        System.out.println(miEstudiante9.promedio4(miEstudiante9.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante9.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante9.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante9.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante9.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante9.getNomMateria5()+" : "+ miEstudiante9.getMateria5());
        System.out.println(miEstudiante9.promedio5(miEstudiante9.materia5));

        System.out.println(miEstudiante10.getNombre());
        System.out.println("Ingrese el nombre de la primera materia: ");
        materia1=miVariable.nextLine();
        miEstudiante10.setNomMateria1(materia1);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante10.getNomMateria1());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante10.getNomMateria1());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante10.setMateria1(notaFinal);
        System.out.println("Nota final de "+miEstudiante10.getNomMateria1()+" : "+ miEstudiante10.getMateria1());
        System.out.println(miEstudiante10.promedio1(miEstudiante10.materia1));
        System.out.println("Ingrese el nombre de la segunda materia: ");
        materia2=miVariable.nextLine();
        miEstudiante10.setNomMateria2(materia2);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante10.getNomMateria2());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante10.getNomMateria2());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante10.setMateria2(notaFinal);
        System.out.println("Nota final de "+miEstudiante10.getNomMateria2()+" : "+ miEstudiante10.getMateria2());
        System.out.println(miEstudiante10.promedio2(miEstudiante10.materia2));
        System.out.println("Ingrese el nombre de la tercera materia: ");
        materia3=miVariable.nextLine();
        miEstudiante10.setNomMateria3(materia3);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante10.getNomMateria3());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante10.getNomMateria3());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante10.setMateria3(notaFinal);
        System.out.println("Nota final de "+miEstudiante10.getNomMateria3()+" : "+ miEstudiante10.getMateria3());
        System.out.println(miEstudiante10.promedio3(miEstudiante10.materia3));
        System.out.println("Ingrese el nombre de la cuarta materia: ");
        materia4=miVariable.nextLine();
        miEstudiante10.setNomMateria4(materia4);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante10.getNomMateria4());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante10.getNomMateria4());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante10.setMateria4(notaFinal);
        System.out.println("Nota final de "+miEstudiante10.getNomMateria4()+" : "+ miEstudiante10.getMateria4());
        System.out.println(miEstudiante10.promedio4(miEstudiante10.materia4));
        System.out.println("Ingrese el nombre de la quinta materia: ");
        materia5=miVariable.nextLine();
        miEstudiante10.setNomMateria5(materia5);
        System.out.println("Ingrese la nota del primer bimestre de la materia: "+miEstudiante10.getNomMateria5());
        nota1=miVariable2.nextDouble();
        System.out.println("Ingrese la nota del segundo bimestre de la materia: "+miEstudiante10.getNomMateria5());
        nota2=miVariable3.nextDouble();
        notaFinal=(nota1+nota2)/2;
        miEstudiante10.setMateria5(notaFinal);
        System.out.println("Nota final de "+miEstudiante10.getNomMateria5()+" : "+ miEstudiante10.getMateria5());
        System.out.println(miEstudiante10.promedio5(miEstudiante10.materia5));


    }
}